"""
regen processed schema

Revision ID: 029f48a368ec
Revises: 2895889d3c6f
Create Date: 2024-08-15 16:57:37.100618

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "029f48a368ec"
down_revision: Union[str, None] = "2895889d3c6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "label_batches",
        "batch_metadata",
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        schema="raw",
        postgresql_using="batch_metadata::jsonb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "label_batches",
        "batch_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        schema="raw",
        postgresql_using="batch_metadata::text",
    )
    # ### end Alembic commands ###
