"""added raw naip table

Revision ID: 05712b4e4ff2
Revises: 9b0ea6c56e9e
Create Date: 2024-08-05 14:26:55.328332

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "05712b4e4ff2"
down_revision: Union[str, None] = "9b0ea6c56e9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "naip21",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "other_cols", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="raw",
    )
    op.create_geospatial_index(
        "idx_naip21_geometry",
        "naip21",
        ["geometry"],
        unique=False,
        schema="raw",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_raw_naip21_filename"),
        "naip21",
        ["filename"],
        unique=True,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raw_naip21_filename"), table_name="naip21", schema="raw")
    op.drop_geospatial_index(
        "idx_naip21_geometry",
        table_name="naip21",
        schema="raw",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("naip21", schema="raw")
    # ### end Alembic commands ###
