"""added raw urbanareas table

Revision ID: 065f872acd2e
Revises: 05712b4e4ff2
Create Date: 2024-08-05 14:32:56.249359

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "065f872acd2e"
down_revision: Union[str, None] = "05712b4e4ff2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "urban_areas",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("geoid20", sa.String(), nullable=False),
        sa.Column("name20", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "other_cols", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="raw",
    )
    op.create_geospatial_index(
        "idx_urban_areas_geometry",
        "urban_areas",
        ["geometry"],
        unique=False,
        schema="raw",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_urban_areas_geometry",
        table_name="urban_areas",
        schema="raw",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("urban_areas", schema="raw")
    # ### end Alembic commands ###
