"""updated relationships

Revision ID: 0740935b17a8
Revises: 2e3fc1889bd7
Create Date: 2024-08-12 15:12:28.411019

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0740935b17a8"
down_revision: Union[str, None] = "2e3fc1889bd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "label_batches_naip_qt_ids_fkey",
        "label_batches",
        schema="processed",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "label_batches_naip_qt_ids_fkey",
        "label_batches",
        "naip21_qt",
        ["naip_qt_ids"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###
