"""updated column types

Revision ID: 07eb27ed7e2e
Revises: f483bd82ed7f
Create Date: 2024-12-17 16:35:16.215839

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07eb27ed7e2e"
down_revision: Union[str, None] = "f483bd82ed7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "barns",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('processed.barns_id_seq'::regclass)"),
        schema="processed",
    )
    op.alter_column(
        "barnsparcels",
        "barn_id",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
        schema="processed",
    )
    op.alter_column(
        "cf_annotations",
        "barn_id",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
        schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cf_annotations",
        "barn_id",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="processed",
    )
    op.alter_column(
        "barnsparcels",
        "barn_id",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        schema="processed",
    )
    op.alter_column(
        "barns",
        "id",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('processed.barns_id_seq'::regclass)"),
        schema="processed",
    )
    # ### end Alembic commands ###
