"""permits storage table, changed names

Revision ID: 0b51e4e1a3fe
Revises: f85bb117506e
Create Date: 2025-01-28 19:50:26.237882

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b51e4e1a3fe"
down_revision: Union[str, None] = "f85bb117506e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permits_storage",
        sa.Column("vegetative_inflitration_basin_vib_", sa.String(), nullable=True),
        schema="raw",
    )
    op.drop_column(
        "permits_storage", "vegetative_infiltration_basin_vib_", schema="raw"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permits_storage",
        sa.Column(
            "vegetative_infiltration_basin_vib_",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        schema="raw",
    )
    op.drop_column(
        "permits_storage", "vegetative_inflitration_basin_vib_", schema="raw"
    )
    # ### end Alembic commands ###
