"""permits storage table, changed names

Revision ID: 0d07a05e6e15
Revises: 29855b480973
Create Date: 2025-01-28 19:42:46.193921

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0d07a05e6e15"
down_revision: Union[str, None] = "29855b480973"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permits_storage", schema="raw")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permits_storage",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "facility_id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('raw.permits_storage_facility_id_seq'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("facility_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("confinement", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("open_feedlot", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("management_plan", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "construction_permit", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("npdes_permit", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "swine",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "dairy_cattle",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "beef_cattle",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "chickens",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "turkeys",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "horses",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "sheep_lambs_goats",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("earthen_basin", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("at_system", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "below_buildings_pits", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "below_buildings_pits_deep",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "below_buildings_pit_shallow",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("other", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "outside_formed_concrete", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "outside_concrete_uncovered",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("runoff_control", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("wetland", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("slurry_store", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("solids_settling", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("lagoon_aerobic", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("lagoon_anaerobic", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "sand_settling_lanes", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "settled_open_feedlot_effluent_basin",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "stockpiling_structure_covered",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "stockpiling_structure_uncovered",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "vegetative_infiltration_basin_vib",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "other_cols",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", "facility_id", name="permits_storage_pkey"),
        schema="raw",
    )
    # ### end Alembic commands ###
