"""updated relationships

Revision ID: 1090ab6e17e9
Revises: bb1ebd918af8
Create Date: 2024-08-12 16:28:11.086412

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1090ab6e17e9"
down_revision: Union[str, None] = "bb1ebd918af8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "parcels",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("permit_id", sa.Integer(), nullable=True),
        sa.Column("parcelnumb", sa.String(), nullable=True),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("scity", sa.String(), nullable=True),
        sa.Column("szip", sa.String(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "other_cols", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["permit_id"],
            ["processed.permits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_parcels_geometry",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_parcels_geometry",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("parcels", schema="processed")
    # ### end Alembic commands ###
