"""update db

Revision ID: 18c4ffbd3ae1
Revises: 28c4088bc019
Create Date: 2025-04-09 12:09:30.878374

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "18c4ffbd3ae1"
down_revision: Union[str, None] = "28c4088bc019"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "barnclusterparcels_staging_barn_cluster_id_idx",
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.drop_index(
        "barnclusterparcels_staging_parcel_id_idx",
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnclusterparcels_barn_cluster_id"),
        "barnclusterparcels",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnclusterparcels_parcel_id"),
        "barnclusterparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "barnclusterparcels",
        "barnclusters",
        ["barn_cluster_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "barnclusterparcels",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.alter_column(
        "facilities",
        "facility_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        schema="processed",
    )
    op.alter_column(
        "facilities",
        "geometry",
        existing_type=Geometry(
            from_text="ST_GeomFromEWKT", name="geometry", _spatial_index_reflected=True
        ),
        type_=Geometry(
            srid=26915, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
        ),
        nullable=False,
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_facilities_facility_id"),
        "facilities",
        ["facility_id"],
        unique=True,
        schema="processed",
    )
    op.add_column(
        "facilities_near_permits",
        sa.Column("id", sa.Integer(), nullable=True),
        schema="processed",
    )
    op.alter_column(
        "facilities_near_permits",
        "permit_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        schema="processed",
    )
    op.alter_column(
        "facilities_near_permits",
        "facility_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=False,
        schema="processed",
    )
    op.alter_column(
        "facilities_near_permits",
        "rn",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "facilities_near_permits",
        "permits",
        ["permit_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "facilities_near_permits",
        "facilities",
        ["facility_id"],
        ["facility_id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_index(
        "parcels_staging_facility_id_idx", table_name="parcels", schema="processed"
    )
    op.drop_geospatial_index(
        "parcels_staging_geometry_idx",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_parcels_geometry",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_parcels_facility_id"),
        "parcels",
        ["facility_id"],
        unique=False,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "parcels",
        "facilities",
        ["facility_id"],
        ["facility_id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permit_parcels",
        "permits",
        ["permit_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permit_parcels",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_index(
        "permits_staging_facility_id_idx", table_name="permits", schema="processed"
    )
    op.drop_index(
        "permits_staging_facilityid_idx", table_name="permits", schema="processed"
    )
    op.drop_geospatial_index(
        "permits_staging_geometry_idx",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_permits_geometry",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_permits_facility_id"),
        "permits",
        ["facility_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_permits_facilityid"),
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21",
        ["naip_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21_qt",
        ["naip_qt_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "facilities",
        ["facility_id"],
        ["facility_id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits_storage",
        "permits",
        ["permit_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permits_storage", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_permits_facilityid"),
        table_name="permits",
        schema="processed",
    )
    op.drop_index(
        op.f("ix_processed_permits_facility_id"),
        table_name="permits",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_permits_geometry",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "permits_staging_geometry_idx",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "permits_staging_facilityid_idx",
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.create_index(
        "permits_staging_facility_id_idx",
        "permits",
        ["facility_id"],
        unique=False,
        schema="processed",
    )
    op.drop_constraint(None, "permit_parcels", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permit_parcels", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "parcels", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_parcels_facility_id"),
        table_name="parcels",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_parcels_geometry",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "parcels_staging_geometry_idx",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "parcels_staging_facility_id_idx",
        "parcels",
        ["facility_id"],
        unique=False,
        schema="processed",
    )
    op.drop_constraint(
        None, "facilities_near_permits", schema="processed", type_="foreignkey"
    )
    op.drop_constraint(
        None, "facilities_near_permits", schema="processed", type_="foreignkey"
    )
    op.alter_column(
        "facilities_near_permits",
        "rn",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        schema="processed",
    )
    op.alter_column(
        "facilities_near_permits",
        "facility_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=True,
        schema="processed",
    )
    op.alter_column(
        "facilities_near_permits",
        "permit_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        schema="processed",
    )
    op.drop_column("facilities_near_permits", "id", schema="processed")
    op.drop_index(
        op.f("ix_processed_facilities_facility_id"),
        table_name="facilities",
        schema="processed",
    )
    op.alter_column(
        "facilities",
        "geometry",
        existing_type=Geometry(
            srid=26915, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
        ),
        type_=Geometry(
            from_text="ST_GeomFromEWKT", name="geometry", _spatial_index_reflected=True
        ),
        nullable=True,
        schema="processed",
    )
    op.alter_column(
        "facilities",
        "facility_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        schema="processed",
    )
    op.drop_constraint(
        None, "barnclusterparcels", schema="processed", type_="foreignkey"
    )
    op.drop_constraint(
        None, "barnclusterparcels", schema="processed", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_processed_barnclusterparcels_parcel_id"),
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.drop_index(
        op.f("ix_processed_barnclusterparcels_barn_cluster_id"),
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.create_index(
        "barnclusterparcels_staging_parcel_id_idx",
        "barnclusterparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        "barnclusterparcels_staging_barn_cluster_id_idx",
        "barnclusterparcels",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    # ### end Alembic commands ###
