"""added permit parcel table

Revision ID: 1b8db05541f6
Revises: d61cd9ea8a8c
Create Date: 2025-04-02 16:18:45.440933

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "1b8db05541f6"
down_revision: Union[str, None] = "d61cd9ea8a8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permit_parcels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("permit_id", sa.Integer(), nullable=False),
        sa.Column("parcel_id", sa.String(), nullable=False),
        sa.Column("match_type", sa.String(), nullable=False),
        sa.Column("fuzzy_match_score", sa.Float(), nullable=True),
        sa.Column("distance_meters", sa.Float(), nullable=True),
        sa.Column("is_primary_match", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["processed.parcels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permit_id"],
            ["processed.permits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )

    # First drop the foreign key constraint
    op.drop_constraint(
        "barnclusters_facility_id_fkey",
        "barnclusters",
        schema="processed",
        type_="foreignkey",
    )
    op.drop_column("barnclusters", "facility_id", schema="processed")

    # Now we can safely drop the facilities table
    op.drop_geospatial_index(
        "idx_facilities_geometry",
        table_name="facilities",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("facilities", schema="processed")

    # Continue with other operations
    op.drop_index(
        "barnclusterparcels_staging_barn_cluster_id_idx1",
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.drop_index(
        "barnclusterparcels_staging_parcel_id_idx1",
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnclusterparcels_barn_cluster_id"),
        "barnclusterparcels",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnclusterparcels_parcel_id"),
        "barnclusterparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "barnclusterparcels",
        "barnclusters",
        ["barn_cluster_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "barnclusterparcels",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_geospatial_index(
        "parcels_staging_geometry_idx1",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_parcels_geometry",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_column("parcels", "facility_id", schema="processed")
    op.drop_index(
        "permits_staging_facilityid_idx", table_name="permits", schema="processed"
    )
    op.drop_geospatial_index(
        "permits_staging_geometry_idx",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_permits_geometry",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_permits_facilityid"),
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21",
        ["naip_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21_qt",
        ["naip_qt_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_column("permits", "matched_permit_to_nearby_parcel", schema="processed")
    op.drop_column("permits", "owner_by_fuzzy_owner_match", schema="processed")
    op.drop_column("permits", "parcel_id", schema="processed")
    op.drop_column("permits", "facility_id", schema="processed")
    op.drop_column("permits", "parcel_id_by_fuzzy_owner_match", schema="processed")
    op.drop_column("permits", "fuzzy_match_score", schema="processed")
    op.create_foreign_key(
        None,
        "permits_storage",
        "permits",
        ["permit_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permits_storage", schema="processed", type_="foreignkey")
    op.add_column(
        "permits",
        sa.Column(
            "fuzzy_match_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="processed",
    )
    op.add_column(
        "permits",
        sa.Column(
            "parcel_id_by_fuzzy_owner_match",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        schema="processed",
    )
    op.add_column(
        "permits",
        sa.Column("facility_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="processed",
    )
    op.add_column(
        "permits",
        sa.Column("parcel_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="processed",
    )
    op.add_column(
        "permits",
        sa.Column(
            "owner_by_fuzzy_owner_match",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        schema="processed",
    )
    op.add_column(
        "permits",
        sa.Column(
            "matched_permit_to_nearby_parcel",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        schema="processed",
    )
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_permits_facilityid"),
        table_name="permits",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_permits_geometry",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "permits_staging_geometry_idx",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "permits_staging_facilityid_idx",
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.add_column(
        "parcels",
        sa.Column("facility_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_parcels_geometry",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "parcels_staging_geometry_idx1",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.add_column(
        "barnclusters",
        sa.Column("facility_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="processed",
    )
    op.create_foreign_key(
        "barnclusters_facility_id_fkey",
        "barnclusters",
        "facilities",
        ["facility_id"],
        ["facility_id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_constraint(
        None, "barnclusterparcels", schema="processed", type_="foreignkey"
    )
    op.drop_constraint(
        None, "barnclusterparcels", schema="processed", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_processed_barnclusterparcels_parcel_id"),
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.drop_index(
        op.f("ix_processed_barnclusterparcels_barn_cluster_id"),
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.create_index(
        "barnclusterparcels_staging_parcel_id_idx1",
        "barnclusterparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        "barnclusterparcels_staging_barn_cluster_id_idx1",
        "barnclusterparcels",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.create_geospatial_table(
        "facilities",
        sa.Column("facility_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("facility_id", name="facilities_pkey"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_facilities_geometry",
        "facilities",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_table("permit_parcels", schema="processed")
    # ### end Alembic commands ###
