"""added processed permit storage table

Revision ID: 1d7c1dd97727
Revises: 8338e2ddf375
Create Date: 2025-01-28 20:21:00.259504

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d7c1dd97727"
down_revision: Union[str, None] = "8338e2ddf375"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
