"""added county data

Revision ID: 1e1d0c3f810b
Revises: 87bf2964133d
Create Date: 2025-02-24 15:54:08.396831

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1e1d0c3f810b"
down_revision: Union[str, None] = "87bf2964133d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "counties",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("geoid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "other_cols", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("geoid"),
        schema="raw",
    )
    op.create_geospatial_index(
        "idx_counties_geometry",
        "counties",
        ["geometry"],
        unique=False,
        schema="raw",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_index(
        "permits_staging_facilityid_idx", table_name="permits", schema="processed"
    )
    op.drop_geospatial_index(
        "permits_staging_geometry_idx",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_permits_geometry",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_permits_facilityid"),
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21_qt",
        ["naip_qt_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21",
        ["naip_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits_storage",
        "permits",
        ["permit_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permits_storage", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_permits_facilityid"),
        table_name="permits",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_permits_geometry",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "permits_staging_geometry_idx",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "permits_staging_facilityid_idx",
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_counties_geometry",
        table_name="counties",
        schema="raw",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("counties", schema="raw")
    # ### end Alembic commands ###
