"""updated relationships

Revision ID: 2201900be039
Revises: 0740935b17a8
Create Date: 2024-08-12 15:14:51.844909

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2201900be039"
down_revision: Union[str, None] = "0740935b17a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "label_batches",
        sa.Column("naip_qt_id", postgresql.ARRAY(sa.String()), nullable=False),
        schema="processed",
    )
    op.drop_column("label_batches", "naip_qt_ids", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "label_batches",
        sa.Column("naip_qt_ids", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="processed",
    )
    op.drop_column("label_batches", "naip_qt_id", schema="processed")
    # ### end Alembic commands ###
