"""updatee foreign keys

Revision ID: 24fd55bfd587
Revises: 76d44e9e3e9f
Create Date: 2025-02-05 17:01:06.504303

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24fd55bfd587"
down_revision: Union[str, None] = "76d44e9e3e9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "barnclusters_staging_geometry_idx",
        table_name="barnclusters",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_index(
        "barns_staging_barn_cluster_id_idx", table_name="barns", schema="processed"
    )
    op.drop_geospatial_index(
        "barns_staging_geometry_idx",
        table_name="barns",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_index(
        "cf_annotations_staging_geometry_buffer_idx",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_buffer",
    )
    op.drop_geospatial_index(
        "cf_annotations_staging_geometry_idx",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_index(
        "cf_annotations_staging_raw_coordinates_idx",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="raw_coordinates",
    )
    op.drop_geospatial_index(
        "parcels_staging_geometry_idx",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_parcels_geometry",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_index(
        "permits_staging_facilityid_idx", table_name="permits", schema="processed"
    )
    op.drop_geospatial_index(
        "permits_staging_geometry_idx",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_permits_geometry",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_permits_facilityid"),
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21",
        ["naip_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21_qt",
        ["naip_qt_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits_storage",
        "permits",
        ["permit_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permits_storage", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_permits_facilityid"),
        table_name="permits",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_permits_geometry",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "permits_staging_geometry_idx",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "permits_staging_facilityid_idx",
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_parcels_geometry",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "parcels_staging_geometry_idx",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "cf_annotations_staging_raw_coordinates_idx",
        "cf_annotations",
        ["raw_coordinates"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "cf_annotations_staging_geometry_idx",
        "cf_annotations",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "cf_annotations_staging_geometry_buffer_idx",
        "cf_annotations",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "barns_staging_geometry_idx",
        "barns",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "barns_staging_barn_cluster_id_idx",
        "barns",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.create_geospatial_index(
        "barnclusters_staging_geometry_idx",
        "barnclusters",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###
