"""added processed permit storage table

Revision ID: 2574fb84fb79
Revises: ae0f9283dfe0
Create Date: 2025-01-28 20:28:21.625760

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2574fb84fb79"
down_revision: Union[str, None] = "ae0f9283dfe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
