"""updated relationships

Revision ID: 27acfeb06088
Revises: b42436dd6a08
Create Date: 2024-08-12 15:36:07.336183

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "27acfeb06088"
down_revision: Union[str, None] = "b42436dd6a08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "naip21_qt",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("naip_id", sa.String(), nullable=False),
        sa.Column("is_urban", sa.Boolean(), nullable=False),
        sa.Column("urban_area", sa.Double(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "geometry_buffer",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["naip_id"],
            ["processed.naip21.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_naip21_qt_geometry",
        "naip21_qt",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_naip21_qt_geometry_buffer",
        "naip21_qt",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_naip21_qt_geometry_buffer",
        table_name="naip21_qt",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_buffer",
    )
    op.drop_geospatial_index(
        "idx_naip21_qt_geometry",
        table_name="naip21_qt",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("naip21_qt", schema="processed")
    # ### end Alembic commands ###
