"""set foreign key parcels barns

Revision ID: 28a59bb8836f
Revises: 71c27b4c3663
Create Date: 2024-12-17 17:14:10.895357

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28a59bb8836f"
down_revision: Union[str, None] = "71c27b4c3663"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
