"""update db

Revision ID: 28c4088bc019
Revises: f1c635b6e0ba
Create Date: 2025-04-07 15:59:59.848019

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "28c4088bc019"
down_revision: Union[str, None] = "f1c635b6e0ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "facilities",
        "facility_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        schema="processed",
    )
    op.alter_column(
        "facilities",
        "geometry",
        existing_type=Geometry(
            from_text="ST_GeomFromEWKT", name="geometry", _spatial_index_reflected=True
        ),
        type_=Geometry(
            srid=26915, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
        ),
        nullable=False,
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_facilities_facility_id"),
        "facilities",
        ["facility_id"],
        unique=True,
        schema="processed",
    )
    op.add_column(
        "facilities_near_permits",
        sa.Column("id", sa.Integer(), nullable=True),
        schema="processed",
    )
    op.alter_column(
        "facilities_near_permits",
        "permit_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        schema="processed",
    )
    op.alter_column(
        "facilities_near_permits",
        "facility_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=False,
        schema="processed",
    )
    op.alter_column(
        "facilities_near_permits",
        "rn",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "facilities_near_permits",
        "facilities",
        ["facility_id"],
        ["facility_id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "facilities_near_permits", schema="processed", type_="foreignkey"
    )
    op.alter_column(
        "facilities_near_permits",
        "rn",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        schema="processed",
    )
    op.alter_column(
        "facilities_near_permits",
        "facility_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=True,
        schema="processed",
    )
    op.alter_column(
        "facilities_near_permits",
        "permit_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        schema="processed",
    )
    op.drop_column("facilities_near_permits", "id", schema="processed")
    op.drop_index(
        op.f("ix_processed_facilities_facility_id"),
        table_name="facilities",
        schema="processed",
    )
    op.alter_column(
        "facilities",
        "geometry",
        existing_type=Geometry(
            srid=26915, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
        ),
        type_=Geometry(
            from_text="ST_GeomFromEWKT", name="geometry", _spatial_index_reflected=True
        ),
        nullable=True,
        schema="processed",
    )
    op.alter_column(
        "facilities",
        "facility_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        schema="processed",
    )
    # ### end Alembic commands ###
