"""added labelbatches table

Revision ID: 294fc1ab8f58
Revises: 7c4c30a3cf94
Create Date: 2024-08-14 15:26:23.143758

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "294fc1ab8f58"
down_revision: Union[str, None] = "7c4c30a3cf94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_name", sa.String(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("batch_date", sa.Date(), nullable=False),
        sa.Column("batch_metadata", sa.String(), nullable=False),
        sa.Column(
            "qt_tile_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("n_facilities", sa.Integer(), nullable=False),
        sa.Column(
            "facility_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("label_batches", schema="raw")
    # ### end Alembic commands ###
