"""permits storage table, changed names

Revision ID: 29855b480973
Revises: 28256de9993a
Create Date: 2025-01-28 19:39:45.545361

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29855b480973"
down_revision: Union[str, None] = "28256de9993a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "permits_storage",
        "outside_formed_concrete",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.String(),
        existing_nullable=True,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "permits_storage",
        "outside_formed_concrete",
        existing_type=sa.String(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
        schema="raw",
    )
    # ### end Alembic commands ###
