"""updated relationships

Revision ID: 2aadc4a5dcee
Revises: 84c9b7c641fb
Create Date: 2024-08-13 10:53:52.177133

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2aadc4a5dcee"
down_revision: Union[str, None] = "84c9b7c641fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parcels",
        sa.Column("permit_count", sa.Integer(), nullable=True),
        schema="processed",
    )
    op.add_column(
        "parcels",
        sa.Column("permit_ids", sa.Integer(), nullable=True),
        schema="processed",
    )
    op.drop_constraint(
        "parcels_permit_id_fkey", "parcels", schema="processed", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "parcels",
        "permits",
        ["permit_ids"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_column("parcels", "permit_id", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parcels",
        sa.Column("permit_id", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="processed",
    )
    op.drop_constraint(None, "parcels", schema="processed", type_="foreignkey")
    op.create_foreign_key(
        "parcels_permit_id_fkey",
        "parcels",
        "permits",
        ["permit_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_column("parcels", "permit_ids", schema="processed")
    op.drop_column("parcels", "permit_count", schema="processed")
    # ### end Alembic commands ###
