"""added barns table

Revision ID: 2e1db3b96e44
Revises: 9a61d08e259d
Create Date: 2024-12-17 15:51:49.246242

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "2e1db3b96e44"
down_revision: Union[str, None] = "9a61d08e259d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "barns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("barn_cluster_id", sa.Integer(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_barns_geometry",
        "barns",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_table(
        "barnsparcels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("barn_id", sa.Integer(), nullable=False),
        sa.Column("parcel_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["barn_id"],
            ["processed.barns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["processed.parcels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.drop_table("cf_annotations_parcels_association", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cf_annotations_parcels_association",
        sa.Column(
            "cf_annotation_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("parcel_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["cf_annotation_id"],
            ["processed.cf_annotations.id"],
            name="cf_annotations_parcels_association_cf_annotation_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["processed.parcels.id"],
            name="cf_annotations_parcels_association_parcel_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "cf_annotation_id",
            "parcel_id",
            name="cf_annotations_parcels_association_staging_pkey",
        ),
        schema="processed",
    )
    op.drop_table("barnsparcels", schema="processed")
    op.drop_geospatial_index(
        "idx_barns_geometry",
        table_name="barns",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("barns", schema="processed")
    # ### end Alembic commands ###
