"""added labelbatches table

Revision ID: 2fc9b17118d9
Revises: 4848a1c5cfa1
Create Date: 2024-08-14 10:52:29.493293

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fc9b17118d9"
down_revision: Union[str, None] = "4848a1c5cfa1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
