"""added county data

Revision ID: 33fd9a66f9d3
Revises: d52bd2658b81
Create Date: 2025-02-24 16:06:22.341194

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "33fd9a66f9d3"
down_revision: Union[str, None] = "d52bd2658b81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_counties_geometry",
        table_name="counties",
        schema="raw",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("counties", schema="raw")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "counties",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("geoid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "other_cols",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="counties_pkey"),
        sa.UniqueConstraint("geoid", name="counties_geoid_key"),
        schema="raw",
    )
    op.create_geospatial_index(
        "idx_counties_geometry",
        "counties",
        ["geometry"],
        unique=False,
        schema="raw",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###
