"""add relationships

Revision ID: 34bc74a96eab
Revises: 3ef11a5b2ba1
Create Date: 2024-08-12 12:29:19.366160

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "34bc74a96eab"
down_revision: Union[str, None] = "3ef11a5b2ba1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "permits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("naip_id", sa.String(), nullable=False),
        sa.Column("naip_qt_id", sa.String(), nullable=False),
        sa.Column("facilityid", sa.Integer(), nullable=False),
        sa.Column("facilityna", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("zip", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("county", sa.String(), nullable=True),
        sa.Column("fieldoffic", sa.String(), nullable=True),
        sa.Column("animal_units", sa.Integer(), nullable=True),
        sa.Column("swine_animal_units", sa.Integer(), nullable=True),
        sa.Column("opeartiont", sa.String(), nullable=True),
        sa.Column("cattle_bee", sa.Integer(), nullable=True),
        sa.Column("cattle_b_1", sa.Integer(), nullable=True),
        sa.Column("immature_d", sa.Integer(), nullable=True),
        sa.Column("mature_dai", sa.Integer(), nullable=True),
        sa.Column("cattle_dai", sa.Integer(), nullable=True),
        sa.Column("cattle_vea", sa.Integer(), nullable=True),
        sa.Column("chicken_la", sa.Integer(), nullable=True),
        sa.Column("chicken_pu", sa.Integer(), nullable=True),
        sa.Column("cow_calf", sa.Integer(), nullable=True),
        sa.Column("ducks", sa.Integer(), nullable=True),
        sa.Column("fish___25", sa.Integer(), nullable=True),
        sa.Column("fish_____2", sa.Integer(), nullable=True),
        sa.Column("goats", sa.Integer(), nullable=True),
        sa.Column("horses", sa.Integer(), nullable=True),
        sa.Column("sheep_and", sa.Integer(), nullable=True),
        sa.Column("swine_gest", sa.Integer(), nullable=True),
        sa.Column("swine_gilt", sa.Integer(), nullable=True),
        sa.Column("swine_grow", sa.Integer(), nullable=True),
        sa.Column("swine_nurs", sa.Integer(), nullable=True),
        sa.Column("swine_sow", sa.Integer(), nullable=True),
        sa.Column("swine_wean", sa.Integer(), nullable=True),
        sa.Column("turkey_fin", sa.Integer(), nullable=True),
        sa.Column("turkey_pou", sa.Integer(), nullable=True),
        sa.Column("collection", sa.String(), nullable=True),
        sa.Column("collectedb", sa.String(), nullable=True),
        sa.Column("locationco", sa.String(), nullable=True),
        sa.Column("address_geo", sa.String(), nullable=True),
        sa.Column("lat_geo", sa.Float(), nullable=True),
        sa.Column("lng_geo", sa.Float(), nullable=True),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column(
            "geometry",
            Geometry(
                geometry_type="POINT",
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "other_cols", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["naip_id"],
            ["processed.naip21.id"],
        ),
        sa.ForeignKeyConstraint(
            ["naip_qt_id"],
            ["processed.naip21_qt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_permits_geometry",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_permits_facilityid"),
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.create_geospatial_table(
        "parcels",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("permit_id", sa.Integer(), nullable=True),
        sa.Column("parcelnumb", sa.String(), nullable=True),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("scity", sa.String(), nullable=True),
        sa.Column("szip", sa.String(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "other_cols", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["permit_id"],
            ["processed.permits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_parcels_geometry",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.alter_column(
        "cf_annotations",
        "tile_id",
        new_column_name="naip_id",
        type_=sa.String(),
        existing_type=sa.String(),
        nullable=False,
        schema="raw",
    )

    op.alter_column(
        "cf_annotations",
        "qt_tile_id",
        new_column_name="naip_qt_id",
        type_=sa.String(),
        existing_type=sa.String(),
        nullable=False,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cf_annotations",
        "naip_id",
        new_column_name="tile_id",
        type_=sa.String(),
        existing_type=sa.String(),
        nullable=False,
        schema="raw",
    )

    op.alter_column(
        "cf_annotations",
        "naip_qt_id",
        new_column_name="qt_tile_id",
        type_=sa.String(),
        existing_type=sa.String(),
        nullable=False,
        schema="raw",
    )
    op.drop_geospatial_index(
        "idx_parcels_geometry",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("parcels", schema="processed")
    op.drop_index(
        op.f("ix_processed_permits_facilityid"),
        table_name="permits",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_permits_geometry",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("permits", schema="processed")
    # ### end Alembic commands ###
