"""added all processed tables

Revision ID: 3560b08b2d61
Revises: cef69b708dcd
Create Date: 2024-08-13 16:51:55.181081

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3560b08b2d61"
down_revision: Union[str, None] = "cef69b708dcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parcels",
        "raw_ids",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        type_=postgresql.ARRAY(sa.Text()),
        existing_nullable=True,
        schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parcels",
        "raw_ids",
        existing_type=postgresql.ARRAY(sa.Text()),
        type_=postgresql.ARRAY(sa.INTEGER()),
        existing_nullable=True,
        schema="processed",
    )
    # ### end Alembic commands ###
