"""updated labelbatchesraw col types

Revision ID: 3eae41021b8f
Revises: f89cce8d42e4
Create Date: 2024-08-05 15:40:13.284823

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3eae41021b8f"
down_revision: Union[str, None] = "f89cce8d42e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "label_batches",
        "facility_ids",
        existing_type=sa.VARCHAR(),
        type_=sa.ARRAY(sa.Integer()),
        existing_nullable=False,
        postgresql_using="string_to_array(facility_ids, ',')::integer[]",
        schema="raw",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "label_batches",
        "facility_ids",
        existing_type=postgresql.ARRAY(sa.Integer()),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        schema="raw",
    )
    # ### end Alembic commands ###
