"""added processed permit storage table

Revision ID: 3ed61ecf9a63
Revises: 0b51e4e1a3fe
Create Date: 2025-01-28 20:11:34.029574

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ed61ecf9a63"
down_revision: Union[str, None] = "0b51e4e1a3fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permits_storage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("facility_id", sa.Integer(), nullable=True),
        sa.Column("facility_name", sa.String(), nullable=False),
        sa.Column("confinement", sa.Boolean(), nullable=True),
        sa.Column("open_feedlot", sa.Boolean(), nullable=True),
        sa.Column("management_plan", sa.Boolean(), nullable=True),
        sa.Column("construction_permit", sa.Boolean(), nullable=True),
        sa.Column("npdes_permit", sa.Boolean(), nullable=True),
        sa.Column("lagoon_aerobic", sa.Boolean(), nullable=True),
        sa.Column("lagoon_anaerobic", sa.Boolean(), nullable=True),
        sa.Column("earthen_basin", sa.Boolean(), nullable=True),
        sa.Column("at_system", sa.Boolean(), nullable=True),
        sa.Column("below_buildings_pits", sa.Boolean(), nullable=True),
        sa.Column("below_buildings_pits_deep", sa.Boolean(), nullable=True),
        sa.Column("below_buildings_pit_shallow", sa.Boolean(), nullable=True),
        sa.Column("storage_other", sa.Boolean(), nullable=True),
        sa.Column("outside_formed_concrete", sa.Boolean(), nullable=True),
        sa.Column("outside_concrete_uncovered", sa.Boolean(), nullable=True),
        sa.Column("runoff_control", sa.Boolean(), nullable=True),
        sa.Column("wetland", sa.Boolean(), nullable=True),
        sa.Column("slurry_store", sa.Boolean(), nullable=True),
        sa.Column("solids_settling", sa.Boolean(), nullable=True),
        sa.Column("sand_settling_lanes", sa.Boolean(), nullable=True),
        sa.Column("settled_open_feedlot_effluent_basin", sa.Boolean(), nullable=True),
        sa.Column("stockpiling_structure_covered", sa.Boolean(), nullable=True),
        sa.Column("stockpiling_structure_uncovered", sa.Boolean(), nullable=True),
        sa.Column("vegetative_inflitration_basin_vib_", sa.Boolean(), nullable=True),
        sa.Column("permits_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["permits_id"],
            ["processed.permits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facility_id"),
        schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permits_storage", schema="processed")
    # ### end Alembic commands ###
