"""add relationship naip->naip_qt

Revision ID: 3ef11a5b2ba1
Revises: b17bc09e0923
Create Date: 2024-08-09 11:55:54.177261

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3ef11a5b2ba1"
down_revision: Union[str, None] = "b17bc09e0923"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "naip21",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "other_cols", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_naip21_geometry",
        "naip21",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_naip21_filename"),
        "naip21",
        ["filename"],
        unique=True,
        schema="processed",
    )
    op.create_geospatial_table(
        "naip21_qt",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("naip_id", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "geometry_buffer",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("is_urban", sa.Boolean(), nullable=False),
        sa.Column("urban_area", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["naip_id"],
            ["processed.naip21.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_naip21_qt_geometry",
        "naip21_qt",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_naip21_qt_geometry_buffer",
        "naip21_qt",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_naip21_qt_geometry_buffer",
        table_name="naip21_qt",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_buffer",
    )
    op.drop_geospatial_index(
        "idx_naip21_qt_geometry",
        table_name="naip21_qt",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("naip21_qt", schema="processed")
    op.drop_index(
        op.f("ix_processed_naip21_filename"), table_name="naip21", schema="processed"
    )
    op.drop_geospatial_index(
        "idx_naip21_geometry",
        table_name="naip21",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("naip21", schema="processed")
    # ### end Alembic commands ###
