"""added type vars to permits

Revision ID: 42e1e969e355
Revises: 029f48a368ec
Create Date: 2024-08-15 20:59:37.610744

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42e1e969e355"
down_revision: Union[str, None] = "029f48a368ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permits",
        sa.Column("animal_type", sa.String(), nullable=True),
        schema="processed",
    )
    op.add_column(
        "permits",
        sa.Column("swine_type", sa.String(), nullable=True),
        schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("permits", "swine_type", schema="processed")
    op.drop_column("permits", "animal_type", schema="processed")
    # ### end Alembic commands ###
