"""added labelbatches table

Revision ID: 4848a1c5cfa1
Revises: 8e0f94a6f841
Create Date: 2024-08-14 10:51:12.253498

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4848a1c5cfa1"
down_revision: Union[str, None] = "8e0f94a6f841"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_name", sa.String(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("batch_date", sa.Date(), nullable=False),
        sa.Column("batch_metadata", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_name"),
        schema="processed",
    )
    op.add_column(
        "cf_annotations",
        sa.Column("batch_name", sa.String(), nullable=True),
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "label_batches",
        ["batch_name"],
        ["batch_name"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.add_column(
        "naip21_qt",
        sa.Column("batch_name", sa.String(), nullable=True),
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "naip21_qt",
        "label_batches",
        ["batch_name"],
        ["batch_name"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "naip21_qt", schema="processed", type_="foreignkey")
    op.drop_column("naip21_qt", "batch_name", schema="processed")
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_column("cf_annotations", "batch_name", schema="processed")
    op.drop_table("label_batches", schema="processed")
    # ### end Alembic commands ###
