"""added processed permit storage table

Revision ID: 49ce7927171c
Revises: 3ed61ecf9a63
Create Date: 2025-01-28 20:16:22.664448

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49ce7927171c"
down_revision: Union[str, None] = "3ed61ecf9a63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("permits_storage", "storage_other", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permits_storage",
        sa.Column("storage_other", sa.BOOLEAN(), autoincrement=False, nullable=True),
        schema="processed",
    )
    # ### end Alembic commands ###
