"""added id column to animal_weights

Revision ID: 5559c8f23bc8
Revises: 7bd2d736c5af
Create Date: 2025-01-23 11:53:27.905014

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5559c8f23bc8"
down_revision: Union[str, None] = "7bd2d736c5af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal_weights",
        sa.Column("id", sa.Integer(), nullable=False),
        schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("animal_weights", "id", schema="processed")
    # ### end Alembic commands ###
