"""updated relationships

Revision ID: 5a7e55bd512e
Revises: 9c0fb79171f6
Create Date: 2024-08-12 15:17:43.817898

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a7e55bd512e"
down_revision: Union[str, None] = "9c0fb79171f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "label_batches",
        sa.Column("naip_qt_id", postgresql.ARRAY(sa.String()), nullable=False),
        schema="processed",
    )
    op.drop_column("label_batches", "naip_qt_ids", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "label_batches",
        sa.Column(
            "naip_qt_ids",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        schema="processed",
    )
    op.drop_column("label_batches", "naip_qt_id", schema="processed")
    # ### end Alembic commands ###
