"""permits storage table, changed names

Revision ID: 5ef28f3abcae
Revises: 0d07a05e6e15
Create Date: 2025-01-28 19:43:04.662755

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5ef28f3abcae"
down_revision: Union[str, None] = "0d07a05e6e15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permits_storage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("facility_id", sa.Integer(), nullable=True),
        sa.Column("facility_name", sa.String(), nullable=False),
        sa.Column("confinement", sa.String(), nullable=True),
        sa.Column("open_feedlot", sa.String(), nullable=True),
        sa.Column("management_plan", sa.String(), nullable=True),
        sa.Column("construction_permit", sa.String(), nullable=True),
        sa.Column("npdes_permit", sa.String(), nullable=True),
        sa.Column("swine", sa.Float(), nullable=True),
        sa.Column("dairy_cattle", sa.Float(), nullable=True),
        sa.Column("beef_cattle", sa.Float(), nullable=True),
        sa.Column("chickens", sa.Float(), nullable=True),
        sa.Column("turkeys", sa.Float(), nullable=True),
        sa.Column("horses", sa.Float(), nullable=True),
        sa.Column("sheep_lambs_goats", sa.Float(), nullable=True),
        sa.Column("earthen_basin", sa.String(), nullable=True),
        sa.Column("at_system", sa.String(), nullable=True),
        sa.Column("below_buildings_pits", sa.String(), nullable=True),
        sa.Column("below_buildings_pits_deep", sa.String(), nullable=True),
        sa.Column("below_buildings_pit_shallow", sa.String(), nullable=True),
        sa.Column("other", sa.String(), nullable=True),
        sa.Column("outside_formed_concrete", sa.String(), nullable=True),
        sa.Column("outside_concrete_uncovered", sa.String(), nullable=True),
        sa.Column("runoff_control", sa.String(), nullable=True),
        sa.Column("wetland", sa.String(), nullable=True),
        sa.Column("slurry_store", sa.String(), nullable=True),
        sa.Column("solids_settling", sa.String(), nullable=True),
        sa.Column("lagoon_aerobic", sa.String(), nullable=True),
        sa.Column("lagoon_anaerobic", sa.String(), nullable=True),
        sa.Column("sand_settling_lanes", sa.String(), nullable=True),
        sa.Column("settled_open_feedlot_effluent_basin", sa.String(), nullable=True),
        sa.Column("stockpiling_structure_covered", sa.String(), nullable=True),
        sa.Column("stockpiling_structure_uncovered", sa.String(), nullable=True),
        sa.Column("vegetative_infiltration_basin_vib", sa.String(), nullable=True),
        sa.Column(
            "other_cols", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facility_id"),
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permits_storage", schema="raw")
    # ### end Alembic commands ###
