"""permits storage table, changed names

Revision ID: 6718a682fc16
Revises: 967ca2a026ed
Create Date: 2025-01-28 19:35:07.163011

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6718a682fc16"
down_revision: Union[str, None] = "967ca2a026ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permits_storage", schema="raw")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permits_storage",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('raw.permits_storage_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("facilityid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("facilityname", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("confinement", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("openfeedlot", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("managementplan", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "constructionpermit", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("npdespermit", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "swine",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "dairycattle",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "beefcattle",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "chickens",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "turkeys",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "horses",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "sheep_lambs_goats",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("earthenbasin", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("atsystem", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "belowbuildingspits", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "belowbuildingspits_deep", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "belowbuildingspit_shallow",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("other", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "outsideformedconcrete", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "outsideconcrete_uncovered",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("runoffcontrol", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("wetland", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("slurrystore", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("solidssettling", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("lagoon_aerobic", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("lagoon_anaerobic", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "sandsettlinglanes", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "settledopenfeedloteffluentbasin",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "stockpilingstructure_covered",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "stockpilingstructure_uncovered",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "vegetativeinfiltrationbasin_vib",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "other_cols",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="permits_storage_pkey"),
        sa.UniqueConstraint("facilityid", name="permits_storage_facilityid_key"),
        schema="raw",
    )
    # ### end Alembic commands ###
