"""re-introduced lists to cfannotation cols

Revision ID: 681a2d3fa3f6
Revises: a7c7fa08b023
Create Date: 2024-08-05 16:59:07.696944

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "681a2d3fa3f6"
down_revision: Union[str, None] = "a7c7fa08b023"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
