"""updated relationships

Revision ID: 69f0436cbdaa
Revises: 5a7e55bd512e
Create Date: 2024-08-12 15:19:03.524207

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69f0436cbdaa"
down_revision: Union[str, None] = "5a7e55bd512e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
