"""added TAM column to animal_weights

Revision ID: 6beedab42cee
Revises: 24fd55bfd587
Create Date: 2025-02-06 17:06:26.492778

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6beedab42cee"
down_revision: Union[str, None] = "24fd55bfd587"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal_weights",
        sa.Column("avg_max_weight_lbs", sa.Float(), nullable=True),
        schema="processed",
    )
    op.add_column(
        "animal_weights",
        sa.Column("avg_max_weight_kgs", sa.Float(), nullable=True),
        schema="processed",
    )
    op.add_column(
        "animal_weights",
        sa.Column("TAM_kgs", sa.Float(), nullable=True),
        schema="processed",
    )
    op.drop_column("animal_weights", "avg_weight_kgs", schema="processed")
    op.drop_column("animal_weights", "avg_weight_lbs", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal_weights",
        sa.Column(
            "avg_weight_lbs",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="processed",
    )
    op.add_column(
        "animal_weights",
        sa.Column(
            "avg_weight_kgs",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="processed",
    )
    op.drop_column("animal_weights", "TAM_kgs", schema="processed")
    op.drop_column("animal_weights", "avg_max_weight_kgs", schema="processed")
    op.drop_column("animal_weights", "avg_max_weight_lbs", schema="processed")
    # ### end Alembic commands ###
