"""implement foreign keys again

Revision ID: 71c27b4c3663
Revises: 816cb0bc34f3
Create Date: 2024-12-17 17:07:48.365802

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71c27b4c3663"
down_revision: Union[str, None] = "816cb0bc34f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "barnsparcels_staging_barn_id_idx",
        table_name="barnsparcels",
        schema="processed",
    )
    op.drop_index(
        "barnsparcels_staging_parcel_id_idx",
        table_name="barnsparcels",
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnsparcels_barn_id"),
        "barnsparcels",
        ["barn_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnsparcels_parcel_id"),
        "barnsparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "barnsparcels",
        "barns",
        ["barn_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "barnsparcels",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "barnsparcels", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "barnsparcels", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_barnsparcels_parcel_id"),
        table_name="barnsparcels",
        schema="processed",
    )
    op.drop_index(
        op.f("ix_processed_barnsparcels_barn_id"),
        table_name="barnsparcels",
        schema="processed",
    )
    op.create_index(
        "barnsparcels_staging_parcel_id_idx",
        "barnsparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        "barnsparcels_staging_barn_id_idx",
        "barnsparcels",
        ["barn_id"],
        unique=False,
        schema="processed",
    )
    # ### end Alembic commands ###
