"""updatee foreign keys

Revision ID: 76d44e9e3e9f
Revises: f9330d065d95
Create Date: 2025-02-05 16:30:06.952589

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76d44e9e3e9f"
down_revision: Union[str, None] = "f9330d065d95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "barnclusterparcels_staging_barn_cluster_id_idx",
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.drop_index(
        "barnclusterparcels_staging_parcel_id_idx",
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnclusterparcels_barn_cluster_id"),
        "barnclusterparcels",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnclusterparcels_parcel_id"),
        "barnclusterparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "barnclusterparcels",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "barnclusterparcels",
        "barnclusters",
        ["barn_cluster_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_geospatial_index(
        "idx_barnclusters_geometry",
        "barnclusters",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_barns_geometry",
        "barns",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_barns_barn_cluster_id"),
        "barns",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "barns",
        "barnclusters",
        ["barn_cluster_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry",
        "cf_annotations",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry_buffer",
        "cf_annotations",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_cf_annotations_raw_coordinates",
        "cf_annotations",
        ["raw_coordinates"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "barns",
        ["barn_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "naip21_qt",
        ["naip_qt_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "label_batches",
        ["batch_name"],
        ["batch_name"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_geospatial_index(
        "idx_cf_annotations_raw_coordinates",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="raw_coordinates",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_geometry_buffer",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_buffer",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_geometry",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "cf_annotations_staging_raw_coordinates_idx1",
        "cf_annotations",
        ["raw_coordinates"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "cf_annotations_staging_geometry_idx1",
        "cf_annotations",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "cf_annotations_staging_geometry_buffer_idx1",
        "cf_annotations",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_constraint(None, "barns", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_barns_barn_cluster_id"),
        table_name="barns",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_barns_geometry",
        table_name="barns",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "barns_staging_geometry_idx1",
        "barns",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "barns_staging_barn_cluster_id_idx1",
        "barns",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_barnclusters_geometry",
        table_name="barnclusters",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "barnclusters_staging_geometry_idx1",
        "barnclusters",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_constraint(
        None, "barnclusterparcels", schema="processed", type_="foreignkey"
    )
    op.drop_constraint(
        None, "barnclusterparcels", schema="processed", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_processed_barnclusterparcels_parcel_id"),
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.drop_index(
        op.f("ix_processed_barnclusterparcels_barn_cluster_id"),
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.create_index(
        "barnclusterparcels_staging_parcel_id_idx",
        "barnclusterparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        "barnclusterparcels_staging_barn_cluster_id_idx",
        "barnclusterparcels",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    # ### end Alembic commands ###
