"""added labelbatches table

Revision ID: 76f2fbc7dad9
Revises: dc3fa02ff0fc
Create Date: 2024-08-14 13:29:52.778366

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76f2fbc7dad9"
down_revision: Union[str, None] = "dc3fa02ff0fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
