"""added animal weights to db

Revision ID: 7bd2d736c5af
Revises: 797793956c3e
Create Date: 2025-01-23 11:48:45.006311

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bd2d736c5af"
down_revision: Union[str, None] = "797793956c3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animal_weights",
        sa.Column("animal_type", sa.String(), nullable=False),
        sa.Column("avg_weight", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("animal_type"),
        schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("animal_weights", schema="processed")
    # ### end Alembic commands ###
