"""updated relationships

Revision ID: 7c30150bfebd
Revises: 85d9cc0d3c98
Create Date: 2024-08-12 16:12:40.689239

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "7c30150bfebd"
down_revision: Union[str, None] = "85d9cc0d3c98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permits",
        sa.Column("address_geocoded", sa.String(), nullable=True),
        schema="processed",
    )
    op.add_geospatial_column(
        "permits",
        sa.Column(
            "geometry_geocoded",
            Geometry(
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_permits_geometry_geocoded",
        "permits",
        ["geometry_geocoded"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_column("permits", "address_geo", schema="processed")
    op.drop_column("permits", "lng_geo", schema="processed")
    op.drop_column("permits", "lat_geo", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permits",
        sa.Column(
            "lat_geo",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="processed",
    )
    op.add_column(
        "permits",
        sa.Column(
            "lng_geo",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="processed",
    )
    op.add_column(
        "permits",
        sa.Column("address_geo", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_permits_geometry_geocoded",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_geocoded",
    )
    op.drop_geospatial_column("permits", "geometry_geocoded", schema="processed")
    op.drop_column("permits", "address_geocoded", schema="processed")
    # ### end Alembic commands ###
