"""added labelbatches table

Revision ID: 7c4c30a3cf94
Revises: 76f2fbc7dad9
Create Date: 2024-08-14 13:36:58.071983

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c4c30a3cf94"
down_revision: Union[str, None] = "76f2fbc7dad9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "label_batches",
        "qt_tile_ids",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.ARRAY(sa.Text()),
        existing_nullable=False,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "label_batches",
        "qt_tile_ids",
        existing_type=postgresql.ARRAY(sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=False,
        schema="raw",
    )
    # ### end Alembic commands ###
