"""updated relationships, test

Revision ID: 7c5452c01c6b
Revises: 34bc74a96eab
Create Date: 2024-08-12 13:52:04.341987

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c5452c01c6b"
down_revision: Union[str, None] = "34bc74a96eab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_parcels_geometry",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("parcels", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "parcels",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("permit_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("parcelnumb", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("scity", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("szip", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "lat", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "lon", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "other_cols",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["permit_id"], ["processed.permits.id"], name="parcels_permit_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="parcels_pkey"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_parcels_geometry",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###
