"""added processed permit storage table

Revision ID: 8338e2ddf375
Revises: d9f15f2cbf22
Create Date: 2025-01-28 20:19:04.190150

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8338e2ddf375"
down_revision: Union[str, None] = "d9f15f2cbf22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permits_storage",
        sa.Column("permit_id", sa.Integer(), nullable=True),
        schema="processed",
    )
    op.drop_constraint(
        "permits_storage_permits_id_fkey",
        "permits_storage",
        schema="processed",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "permits_storage",
        "permits",
        ["permit_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_column("permits_storage", "permits_id", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permits_storage",
        sa.Column("permits_id", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="processed",
    )
    op.drop_constraint(None, "permits_storage", schema="processed", type_="foreignkey")
    op.create_foreign_key(
        "permits_storage_permits_id_fkey",
        "permits_storage",
        "permits",
        ["permits_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_column("permits_storage", "permit_id", schema="processed")
    # ### end Alembic commands ###
