"""added id to association table

Revision ID: 8518c66d51fb
Revises: 4232529b72f8
Create Date: 2024-12-09 19:07:30.529738

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8518c66d51fb"
down_revision: Union[str, None] = "4232529b72f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "cf_annotations_parcels_association",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "cf_annotations_parcels_association",
        "cf_annotations",
        ["cf_annotation_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None,
        "cf_annotations_parcels_association",
        schema="processed",
        type_="foreignkey",
    )
    op.drop_constraint(
        None,
        "cf_annotations_parcels_association",
        schema="processed",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
