"""added census tract table

Revision ID: 8ba8d5bf8606
Revises: d2d21b68d2c2
Create Date: 2025-03-02 19:04:01.311590

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8ba8d5bf8606"
down_revision: Union[str, None] = "d2d21b68d2c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "census_tracts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("statefp", sa.String(), nullable=False),
        sa.Column("countyfp", sa.String(), nullable=False),
        sa.Column("tractce", sa.String(), nullable=False),
        sa.Column("geoid", sa.String(), nullable=False),
        sa.Column("namelsad", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("geoid"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_census_tracts_geometry",
        "census_tracts",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "census_tracts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("statefp", sa.String(), nullable=False),
        sa.Column("countyfp", sa.String(), nullable=False),
        sa.Column("tractce", sa.String(), nullable=False),
        sa.Column("geoid", sa.String(), nullable=False),
        sa.Column("namelsad", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "other_cols", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("geoid"),
        schema="raw",
    )
    op.create_geospatial_index(
        "idx_census_tracts_geometry",
        "census_tracts",
        ["geometry"],
        unique=False,
        schema="raw",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_geospatial_index(
        "counties_staging_geometry_idx",
        table_name="counties",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("counties", schema="processed")
    op.drop_geospatial_index(
        "idx_counties_geometry",
        table_name="counties",
        schema="raw",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("counties", schema="raw")
    op.drop_index(
        "barnclusterparcels_staging_barn_cluster_id_idx",
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.drop_index(
        "barnclusterparcels_staging_parcel_id_idx",
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnclusterparcels_barn_cluster_id"),
        "barnclusterparcels",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnclusterparcels_parcel_id"),
        "barnclusterparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "barnclusterparcels",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "barnclusterparcels",
        "barnclusters",
        ["barn_cluster_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_geospatial_index(
        "barnclusters_staging_geometry_idx1",
        table_name="barnclusters",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_barnclusters_geometry",
        "barnclusters",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_index(
        "barns_staging_barn_cluster_id_idx1", table_name="barns", schema="processed"
    )
    op.drop_geospatial_index(
        "barns_staging_geometry_idx1",
        table_name="barns",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_barns_geometry",
        "barns",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_barns_barn_cluster_id"),
        "barns",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "barns",
        "barnclusters",
        ["barn_cluster_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_geospatial_index(
        "cf_annotations_staging_geometry_buffer_idx1",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_buffer",
    )
    op.drop_geospatial_index(
        "cf_annotations_staging_geometry_idx1",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_index(
        "cf_annotations_staging_raw_coordinates_idx1",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="raw_coordinates",
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry",
        "cf_annotations",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry_buffer",
        "cf_annotations",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_cf_annotations_raw_coordinates",
        "cf_annotations",
        ["raw_coordinates"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "barns",
        ["barn_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "naip21_qt",
        ["naip_qt_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "label_batches",
        ["batch_name"],
        ["batch_name"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_geospatial_index(
        "parcels_staging_geometry_idx",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_parcels_geometry",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_index(
        "permits_staging_facilityid_idx1", table_name="permits", schema="processed"
    )
    op.drop_geospatial_index(
        "permits_staging_geometry_idx1",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_permits_geometry",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_permits_facilityid"),
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21_qt",
        ["naip_qt_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21",
        ["naip_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits_storage",
        "permits",
        ["permit_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permits_storage", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_permits_facilityid"),
        table_name="permits",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_permits_geometry",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "permits_staging_geometry_idx1",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "permits_staging_facilityid_idx1",
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_parcels_geometry",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "parcels_staging_geometry_idx",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_geospatial_index(
        "idx_cf_annotations_raw_coordinates",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="raw_coordinates",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_geometry_buffer",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_buffer",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_geometry",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "cf_annotations_staging_raw_coordinates_idx1",
        "cf_annotations",
        ["raw_coordinates"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "cf_annotations_staging_geometry_idx1",
        "cf_annotations",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "cf_annotations_staging_geometry_buffer_idx1",
        "cf_annotations",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_constraint(None, "barns", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_barns_barn_cluster_id"),
        table_name="barns",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_barns_geometry",
        table_name="barns",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "barns_staging_geometry_idx1",
        "barns",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "barns_staging_barn_cluster_id_idx1",
        "barns",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_barnclusters_geometry",
        table_name="barnclusters",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "barnclusters_staging_geometry_idx1",
        "barnclusters",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_constraint(
        None, "barnclusterparcels", schema="processed", type_="foreignkey"
    )
    op.drop_constraint(
        None, "barnclusterparcels", schema="processed", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_processed_barnclusterparcels_parcel_id"),
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.drop_index(
        op.f("ix_processed_barnclusterparcels_barn_cluster_id"),
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.create_index(
        "barnclusterparcels_staging_parcel_id_idx",
        "barnclusterparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        "barnclusterparcels_staging_barn_cluster_id_idx",
        "barnclusterparcels",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.create_geospatial_table(
        "counties",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("geoid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("statefp", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "other_cols",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="counties_pkey"),
        sa.UniqueConstraint("geoid", name="counties_geoid_key"),
        schema="raw",
    )
    op.create_geospatial_index(
        "idx_counties_geometry",
        "counties",
        ["geometry"],
        unique=False,
        schema="raw",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "counties",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="counties_staging_pkey"),
        schema="processed",
    )
    op.create_geospatial_index(
        "counties_staging_geometry_idx",
        "counties",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_geospatial_index(
        "idx_census_tracts_geometry",
        table_name="census_tracts",
        schema="raw",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("census_tracts", schema="raw")
    op.drop_geospatial_index(
        "idx_census_tracts_geometry",
        table_name="census_tracts",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("census_tracts", schema="processed")
    # ### end Alembic commands ###
