"""added columns to CFannotations

Revision ID: 8e0f94a6f841
Revises: b120aa8f3bf7
Create Date: 2024-08-14 10:23:38.094659

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8e0f94a6f841"
down_revision: Union[str, None] = "b120aa8f3bf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cf_annotations",
        sa.Column("clipped_annotation", sa.Boolean(), nullable=False),
        schema="processed",
    )
    op.add_column(
        "cf_annotations",
        sa.Column("clipped_annotation_empty", sa.Boolean(), nullable=False),
        schema="processed",
    )
    op.add_geospatial_column(
        "cf_annotations",
        sa.Column(
            "geometry_buffer",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        schema="processed",
    )
    op.add_geospatial_column(
        "cf_annotations",
        sa.Column(
            "raw_coordinates",
            Geometry(spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        schema="processed",
    )
    op.alter_column(
        "cf_annotations",
        "geometry",
        existing_type=Geometry(
            geometry_type="POINT",
            srid=26915,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        type_=Geometry(srid=26915, from_text="ST_GeomFromEWKT", name="geometry"),
        existing_nullable=True,
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry_buffer",
        "cf_annotations",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_cf_annotations_raw_coordinates",
        "cf_annotations",
        ["raw_coordinates"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_column("cf_annotations", "other_cols", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cf_annotations",
        sa.Column(
            "other_cols",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_raw_coordinates",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="raw_coordinates",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_geometry_buffer",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_buffer",
    )
    op.alter_column(
        "cf_annotations",
        "geometry",
        existing_type=Geometry(
            srid=26915, from_text="ST_GeomFromEWKT", name="geometry"
        ),
        type_=Geometry(
            geometry_type="POINT",
            srid=26915,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        existing_nullable=True,
        schema="processed",
    )
    op.drop_geospatial_column("cf_annotations", "raw_coordinates", schema="processed")
    op.drop_geospatial_column("cf_annotations", "geometry_buffer", schema="processed")
    op.drop_column("cf_annotations", "clipped_annotation_empty", schema="processed")
    op.drop_column("cf_annotations", "clipped_annotation", schema="processed")
    # ### end Alembic commands ###
