"""added geometry col

Revision ID: 9670d9fb51b1
Revises: 681a2d3fa3f6
Create Date: 2024-08-05 17:11:06.746418

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9670d9fb51b1"
down_revision: Union[str, None] = "681a2d3fa3f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column(
        "cf_annotations",
        sa.Column(
            "geometry",
            Geometry(
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        schema="raw",
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry",
        "cf_annotations",
        ["geometry"],
        unique=False,
        schema="raw",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_column("cf_annotations", "createdat", schema="raw")
    op.drop_column("cf_annotations", "coordinates", schema="raw")
    op.drop_column("cf_annotations", "attributes", schema="raw")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cf_annotations",
        sa.Column(
            "attributes",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        schema="raw",
    )
    op.add_column(
        "cf_annotations",
        sa.Column(
            "coordinates",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        schema="raw",
    )
    op.add_column(
        "cf_annotations",
        sa.Column("createdat", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="raw",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_geometry",
        table_name="cf_annotations",
        schema="raw",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_column("cf_annotations", "geometry", schema="raw")
    # ### end Alembic commands ###
