"""added permits storeage primary keys

Revision ID: 967ca2a026ed
Revises: 3c86250dee68
Create Date: 2025-01-28 19:03:40.389450

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "967ca2a026ed"
down_revision: Union[str, None] = "3c86250dee68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permits_storage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("facilityid", sa.Integer(), nullable=True),
        sa.Column("facilityname", sa.String(), nullable=False),
        sa.Column("confinement", sa.String(), nullable=True),
        sa.Column("openfeedlot", sa.String(), nullable=True),
        sa.Column("managementplan", sa.String(), nullable=True),
        sa.Column("constructionpermit", sa.String(), nullable=True),
        sa.Column("npdespermit", sa.String(), nullable=True),
        sa.Column("swine", sa.Float(), nullable=True),
        sa.Column("dairycattle", sa.Float(), nullable=True),
        sa.Column("beefcattle", sa.Float(), nullable=True),
        sa.Column("chickens", sa.Float(), nullable=True),
        sa.Column("turkeys", sa.Float(), nullable=True),
        sa.Column("horses", sa.Float(), nullable=True),
        sa.Column("sheep_lambs_goats", sa.Float(), nullable=True),
        sa.Column("earthenbasin", sa.String(), nullable=True),
        sa.Column("atsystem", sa.String(), nullable=True),
        sa.Column("belowbuildingspits", sa.String(), nullable=True),
        sa.Column("belowbuildingspits_deep", sa.String(), nullable=True),
        sa.Column("belowbuildingspit_shallow", sa.String(), nullable=True),
        sa.Column("other", sa.String(), nullable=True),
        sa.Column("outsideformedconcrete", sa.String(), nullable=True),
        sa.Column("outsideconcrete_uncovered", sa.String(), nullable=True),
        sa.Column("runoffcontrol", sa.String(), nullable=True),
        sa.Column("wetland", sa.String(), nullable=True),
        sa.Column("slurrystore", sa.String(), nullable=True),
        sa.Column("solidssettling", sa.String(), nullable=True),
        sa.Column("lagoon_aerobic", sa.String(), nullable=True),
        sa.Column("lagoon_anaerobic", sa.String(), nullable=True),
        sa.Column("sandsettlinglanes", sa.String(), nullable=True),
        sa.Column("settledopenfeedloteffluentbasin", sa.String(), nullable=True),
        sa.Column("stockpilingstructure_covered", sa.String(), nullable=True),
        sa.Column("stockpilingstructure_uncovered", sa.String(), nullable=True),
        sa.Column("vegetativeinfiltrationbasin_vib", sa.String(), nullable=True),
        sa.Column(
            "other_cols", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facilityid"),
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permits_storage", schema="raw")
    # ### end Alembic commands ###
