"""updated cf annotation table

Revision ID: 9a61d08e259d
Revises: 21be0ff31703
Create Date: 2024-12-15 20:45:41.204165

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a61d08e259d"
down_revision: Union[str, None] = "21be0ff31703"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cf_annotations",
        sa.Column("original_ids", postgresql.ARRAY(sa.Text()), nullable=True),
        schema="processed",
    )
    op.add_column(
        "cf_annotations",
        sa.Column("features_merged", sa.Integer(), nullable=True),
        schema="processed",
    )
    op.drop_geospatial_index(
        "cf_annotations_staging_geometry_buffer_idx",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_buffer",
    )
    op.drop_geospatial_index(
        "cf_annotations_staging_geometry_idx",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_index(
        "cf_annotations_staging_raw_coordinates_idx",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="raw_coordinates",
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry",
        "cf_annotations",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry_buffer",
        "cf_annotations",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_cf_annotations_raw_coordinates",
        "cf_annotations",
        ["raw_coordinates"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "label_batches",
        ["batch_name"],
        ["batch_name"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "naip21_qt",
        ["naip_qt_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "cf_annotations_parcels_association",
        "cf_annotations",
        ["cf_annotation_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None,
        "cf_annotations_parcels_association",
        schema="processed",
        type_="foreignkey",
    )
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_geospatial_index(
        "idx_cf_annotations_raw_coordinates",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="raw_coordinates",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_geometry_buffer",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_buffer",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_geometry",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "cf_annotations_staging_raw_coordinates_idx",
        "cf_annotations",
        ["raw_coordinates"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "cf_annotations_staging_geometry_idx",
        "cf_annotations",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "cf_annotations_staging_geometry_buffer_idx",
        "cf_annotations",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_column("cf_annotations", "features_merged", schema="processed")
    op.drop_column("cf_annotations", "original_ids", schema="processed")
    # ### end Alembic commands ###
