"""update label_batches

Revision ID: 9bda6f3aa257
Revises: f60b55ce3f92
Create Date: 2024-08-15 15:42:07.281238

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bda6f3aa257"
down_revision: Union[str, None] = "f60b55ce3f92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
