"""update label_batches

Revision ID: a8b6eb7ef41f
Revises: f1c1fd57562d
Create Date: 2024-08-15 16:42:12.306062

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8b6eb7ef41f"
down_revision: Union[str, None] = "f1c1fd57562d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
