"""added processed urban table

Revision ID: b17bc09e0923
Revises: 8a85df038db6
Create Date: 2024-08-09 11:28:17.299863

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b17bc09e0923"
down_revision: Union[str, None] = "8a85df038db6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "urban_areas",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("geoid20", sa.String(), nullable=False),
        sa.Column("name20", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "other_cols", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_urban_areas_geometry",
        "urban_areas",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.add_column(
        "permits", sa.Column("totalanima", sa.Integer(), nullable=True), schema="raw"
    )
    op.drop_column("permits", "swine_animal_units", schema="raw")
    op.drop_column("permits", "distance_km", schema="raw")
    op.drop_column("permits", "address_geo", schema="raw")
    op.drop_column("permits", "animal_units", schema="raw")
    op.drop_column("permits", "lat_geo", schema="raw")
    op.drop_column("permits", "lng_geo", schema="raw")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permits",
        sa.Column(
            "lng_geo",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="raw",
    )
    op.add_column(
        "permits",
        sa.Column(
            "lat_geo",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="raw",
    )
    op.add_column(
        "permits",
        sa.Column("animal_units", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="raw",
    )
    op.add_column(
        "permits",
        sa.Column("address_geo", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="raw",
    )
    op.add_column(
        "permits",
        sa.Column(
            "distance_km",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="raw",
    )
    op.add_column(
        "permits",
        sa.Column(
            "swine_animal_units", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        schema="raw",
    )
    op.drop_column("permits", "totalanima", schema="raw")
    op.drop_geospatial_index(
        "idx_urban_areas_geometry",
        table_name="urban_areas",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("urban_areas", schema="processed")
    # ### end Alembic commands ###
