"""updated relationships

Revision ID: b42436dd6a08
Revises: fee5b7795652
Create Date: 2024-08-12 15:31:23.180057

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b42436dd6a08"
down_revision: Union[str, None] = "fee5b7795652"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ### commands auto generated by Alembic - please adjust! ###
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_parcels_geometry",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )

    # Use raw SQL to drop tables with CASCADE
    op.execute("DROP TABLE IF EXISTS processed.parcels CASCADE")
    op.execute("DROP TABLE IF EXISTS processed.permits CASCADE")
    op.execute("DROP TABLE IF EXISTS processed.label_batches CASCADE")
    op.execute("DROP TABLE IF EXISTS processed.naip21_qt CASCADE")
    op.execute("DROP TABLE IF EXISTS processed.cf_annotations CASCADE")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "cf_annotations",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("naip_qt_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("n_annotations", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("batch_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("datasetid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("itemid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("label", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("creator", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                geometry_type="POINT",
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "other_cols",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["batch_name"],
            ["processed.label_batches.batch_name"],
            name="cf_annotations_batch_name_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["naip_qt_id"],
            ["processed.naip21_qt.id"],
            name="cf_annotations_naip_qt_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="cf_annotations_pkey"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry",
        "cf_annotations",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "naip21_qt",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("naip_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "geometry_buffer",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_urban", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "urban_area",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["naip_id"], ["processed.naip21.id"], name="naip21_qt_naip_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="naip21_qt_pkey"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_naip21_qt_geometry_buffer",
        "naip21_qt",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_naip21_qt_geometry",
        "naip21_qt",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_table(
        "label_batches",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('processed.label_batches_id_seq'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("batch_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("batch_size", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("batch_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("batch_metadata", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("n_facilities", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "facility_ids",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("naip_qt_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["naip_qt_id"],
            ["processed.naip21_qt.id"],
            name="label_batches_naip_qt_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="label_batches_pkey"),
        sa.UniqueConstraint("batch_name", name="label_batches_batch_name_key"),
        schema="processed",
    )
    op.create_geospatial_table(
        "permits",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('processed.permits_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("naip_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("naip_qt_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("facilityid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("facilityna", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("state", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("zip", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("county", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("fieldoffic", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("animal_units", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "swine_animal_units", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("opeartiont", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("cattle_bee", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cattle_b_1", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("immature_d", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("mature_dai", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cattle_dai", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cattle_vea", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("chicken_la", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("chicken_pu", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cow_calf", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("ducks", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("fish___25", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("fish_____2", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("goats", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("horses", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("sheep_and", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("swine_gest", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("swine_gilt", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("swine_grow", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("swine_nurs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("swine_sow", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("swine_wean", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("turkey_fin", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("turkey_pou", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("collection", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("collectedb", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("locationco", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("address_geo", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "lat_geo",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "lng_geo",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "distance_km",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "geometry",
            Geometry(
                geometry_type="POINT",
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "other_cols",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["naip_id"], ["processed.naip21.id"], name="permits_naip_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["naip_qt_id"], ["processed.naip21_qt.id"], name="permits_naip_qt_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="permits_pkey"),
        schema="processed",
    )
    op.create_index(
        "ix_processed_permits_facilityid",
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_permits_geometry",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "parcels",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("permit_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("parcelnumb", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("scity", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("szip", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "lat", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "lon", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "other_cols",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["permit_id"], ["processed.permits.id"], name="parcels_permit_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="parcels_pkey"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_parcels_geometry",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###
