"""updated cfannotation column types

Revision ID: b882a2aacf73
Revises: c2c8e4247d4a
Create Date: 2024-08-05 16:54:29.527492

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b882a2aacf73"
down_revision: Union[str, None] = "c2c8e4247d4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cf_annotations",
        "createdat",
        existing_type=sa.DATE(),
        type_=sa.String(),
        existing_nullable=False,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cf_annotations",
        "createdat",
        existing_type=sa.String(),
        type_=sa.DATE(),
        existing_nullable=False,
        schema="raw",
    )
    # ### end Alembic commands ###
