"""check for changes

Revision ID: bbfff30040f6
Revises: dd74f72f72ec
Create Date: 2024-03-21 11:23:42.123456

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbfff30040f6"
down_revision: Union[str, None] = "dd74f72f72ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal_weights",
        sa.Column("avg_max_weight_sd_lbs", sa.Float(), nullable=True),
        schema="processed",
    )
    op.add_column(
        "animal_weights",
        sa.Column("TAM_lbs", sa.Float(), nullable=True),
        schema="processed",
    )
    op.drop_column("animal_weights", "avg_max_weight_kgs", schema="processed")
    op.drop_column("animal_weights", "TAM_kgs", schema="processed")


def downgrade() -> None:
    op.add_column(
        "animal_weights",
        sa.Column("TAM_kgs", sa.Float(), nullable=True),
        schema="processed",
    )
    op.add_column(
        "animal_weights",
        sa.Column("avg_max_weight_kgs", sa.Float(), nullable=True),
        schema="processed",
    )
    op.drop_column("animal_weights", "TAM_lbs", schema="processed")
    op.drop_column("animal_weights", "avg_max_weight_sd_lbs", schema="processed")
    # ### end Alembic commands ###
