"""update label_batches

Revision ID: bc3a16ea76b5
Revises: 9bda6f3aa257
Create Date: 2024-08-15 15:42:42.821238

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc3a16ea76b5"
down_revision: Union[str, None] = "9bda6f3aa257"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
