"""moved label_batches to right schema

Revision ID: bf649c221226
Revises: fd91d2bb8358
Create Date: 2024-08-05 17:33:32.710531

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bf649c221226"
down_revision: Union[str, None] = "fd91d2bb8358"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_name", sa.String(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("batch_date", sa.Date(), nullable=False),
        sa.Column("batch_metadata", sa.String(), nullable=False),
        sa.Column("qt_tile_ids", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("n_facilities", sa.Integer(), nullable=False),
        sa.Column("facility_ids", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="raw",
    )
    op.drop_table("label_batches")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label_batches",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("batch_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("batch_size", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("batch_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("batch_metadata", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "qt_tile_ids",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("n_facilities", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "facility_ids",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="label_batches_pkey"),
    )
    op.drop_table("label_batches", schema="raw")
    # ### end Alembic commands ###
