"""added cf_annotations table

Revision ID: c2c8e4247d4a
Revises: ff5fda5f179e
Create Date: 2024-08-05 16:45:55.250465

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c2c8e4247d4a"
down_revision: Union[str, None] = "ff5fda5f179e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cf_annotations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("qt_tile_id", sa.String(), nullable=False),
        sa.Column("tile_id", sa.String(), nullable=False),
        sa.Column("n_annotations", sa.Integer(), nullable=False),
        sa.Column("batch_name", sa.String(), nullable=False),
        sa.Column("datasetid", sa.String(), nullable=False),
        sa.Column("itemid", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("attributes", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("coordinates", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("creator", sa.String(), nullable=False),
        sa.Column("createdat", sa.Date(), nullable=False),
        sa.Column(
            "other_cols", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cf_annotations", schema="raw")
    # ### end Alembic commands ###
