"""created annotation parcel swap table

Revision ID: c7398f351728
Revises: fe0f9e589dd8
Create Date: 2024-12-09 18:52:23.122447

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "c7398f351728"
down_revision: Union[str, None] = "fe0f9e589dd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cf_annotations_parcels_association",
        sa.Column("cf_annotation_id", sa.String(), nullable=False),
        sa.Column("parcel_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cf_annotation_id"],
            ["processed.cf_annotations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["processed.parcels.id"],
        ),
        sa.PrimaryKeyConstraint("cf_annotation_id", "parcel_id"),
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_parcels_geometry",
        table_name="parcels",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("parcels")
    op.drop_column("cf_annotations", "parcel_id", schema="processed")
    op.drop_geospatial_index(
        "parcels_staging_geometry_idx1",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_parcels_geometry",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_index(
        "permits_staging_facilityid_idx", table_name="permits", schema="processed"
    )
    op.drop_geospatial_index(
        "permits_staging_geometry_idx",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_permits_geometry",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_permits_facilityid"),
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21",
        ["naip_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21_qt",
        ["naip_qt_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_permits_facilityid"),
        table_name="permits",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_permits_geometry",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "permits_staging_geometry_idx",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "permits_staging_facilityid_idx",
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_parcels_geometry",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "parcels_staging_geometry_idx1",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.add_column(
        "cf_annotations",
        sa.Column("parcel_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="processed",
    )
    op.create_geospatial_table(
        "parcels",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("parcelnumb", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("owner", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("county", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("scity", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("szip", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "lat", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "lon", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_geospatial_index(
        "idx_parcels_geometry",
        "parcels",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_table("cf_annotations_parcels_association", schema="processed")
    # ### end Alembic commands ###
