"""added weight type columns to animal_weights

Revision ID: cbde25f8f1aa
Revises: 5559c8f23bc8
Create Date: 2025-01-24 11:41:25.648962

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbde25f8f1aa"
down_revision: Union[str, None] = "5559c8f23bc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal_weights",
        sa.Column("avg_weight_lbs", sa.Float(), nullable=True),
        schema="processed",
    )
    op.add_column(
        "animal_weights",
        sa.Column("avg_weight_kgs", sa.Float(), nullable=True),
        schema="processed",
    )
    op.drop_column("animal_weights", "avg_weight", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animal_weights",
        sa.Column(
            "avg_weight",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        schema="processed",
    )
    op.drop_column("animal_weights", "avg_weight_kgs", schema="processed")
    op.drop_column("animal_weights", "avg_weight_lbs", schema="processed")
    # ### end Alembic commands ###
