"""updated relationships

Revision ID: d07f51383467
Revises: f75e279d1160
Create Date: 2024-08-13 11:30:19.759014

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d07f51383467"
down_revision: Union[str, None] = "f75e279d1160"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parcels",
        sa.Column("raw_ids", postgresql.ARRAY(sa.Integer()), nullable=True),
        schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parcels", "raw_ids", schema="processed")
    # ### end Alembic commands ###
