"""added county data

Revision ID: d2d21b68d2c2
Revises: 644108dc5943
Create Date: 2025-02-24 16:25:17.866768

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2d21b68d2c2"
down_revision: Union[str, None] = "644108dc5943"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("counties", "geoid20", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "counties",
        sa.Column("geoid20", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="processed",
    )
    # ### end Alembic commands ###
