"""added columns for fuzzy permit to parcel match, based on owner name

Revision ID: d61cd9ea8a8c
Revises: 16c03e93dd44
Create Date: 2025-03-11 12:54:36.574846

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d61cd9ea8a8c"
down_revision: Union[str, None] = "16c03e93dd44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "census_tracts_staging_geometry_idx",
        table_name="census_tracts",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_census_tracts_geometry",
        "census_tracts",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.add_column(
        "permits",
        sa.Column("owner_by_fuzzy_owner_match", sa.String(), nullable=True),
        schema="processed",
    )
    op.add_column(
        "permits",
        sa.Column("fuzzy_match_score", sa.Float(), nullable=True),
        schema="processed",
    )
    op.add_column(
        "permits",
        sa.Column("parcel_id_by_fuzzy_owner_match", sa.String(), nullable=True),
        schema="processed",
    )
    op.drop_index(
        "permits_staging_facilityid_idx", table_name="permits", schema="processed"
    )
    op.drop_geospatial_index(
        "permits_staging_geometry_idx",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_permits_geometry",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_permits_facilityid"),
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21_qt",
        ["naip_qt_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21",
        ["naip_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "parcels",
        ["parcel_id_by_fuzzy_owner_match"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits_storage",
        "permits",
        ["permit_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permits_storage", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_permits_facilityid"),
        table_name="permits",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_permits_geometry",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "permits_staging_geometry_idx",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "permits_staging_facilityid_idx",
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.drop_column("permits", "parcel_id_by_fuzzy_owner_match", schema="processed")
    op.drop_column("permits", "fuzzy_match_score", schema="processed")
    op.drop_column("permits", "owner_by_fuzzy_owner_match", schema="processed")
    op.drop_geospatial_index(
        "idx_census_tracts_geometry",
        table_name="census_tracts",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "census_tracts_staging_geometry_idx",
        "census_tracts",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###
