"""added processed permit storage table

Revision ID: d9f15f2cbf22
Revises: 49ce7927171c
Create Date: 2025-01-28 20:18:25.065035

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9f15f2cbf22"
down_revision: Union[str, None] = "49ce7927171c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "permits_storage",
        "permits",
        ["permits_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permits_storage", schema="processed", type_="foreignkey")
    # ### end Alembic commands ###
