"""reintroduce parcel merging

Revision ID: dbbc548c5337
Revises: 28a59bb8836f
Create Date: 2024-12-18 15:26:13.007154

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dbbc548c5337"
down_revision: Union[str, None] = "28a59bb8836f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parcels",
        sa.Column("features_merged", sa.Integer(), nullable=True),
        schema="processed",
    )
    op.add_column(
        "parcels",
        sa.Column("original_ids", postgresql.ARRAY(sa.Text()), nullable=True),
        schema="processed",
    )
    op.drop_column("parcels", "raw_ids", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parcels",
        sa.Column(
            "raw_ids", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True
        ),
        schema="processed",
    )
    op.drop_column("parcels", "original_ids", schema="processed")
    op.drop_column("parcels", "features_merged", schema="processed")
    # ### end Alembic commands ###
