"""updated labelbatchesraw id col

Revision ID: e1e565c964a6
Revises: fc3f23f8b7e8
Create Date: 2024-08-05 15:27:50.338130

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1e565c964a6"
down_revision: Union[str, None] = "fc3f23f8b7e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "label_batches", sa.Column("id", sa.Integer(), nullable=False), schema="raw"
    )
    op.drop_column("label_batches", "batch_nr", schema="raw")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "label_batches",
        sa.Column(
            "batch_nr",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('raw.label_batches_batch_nr_seq'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        schema="raw",
    )
    op.drop_column("label_batches", "id", schema="raw")
    # ### end Alembic commands ###
