"""reintroduce parcel merging

Revision ID: e83cba79ae56
Revises: dbbc548c5337
Create Date: 2024-12-18 15:44:07.186110

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e83cba79ae56"
down_revision: Union[str, None] = "dbbc548c5337"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "barnsparcels",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.add_column(
        "parcels",
        sa.Column(
            "original_geoms",
            postgresql.ARRAY(Geometry(from_text="ST_GeomFromEWKT", name="geometry")),
            nullable=True,
        ),
        schema="processed",
    )
    op.drop_geospatial_index(
        "parcels_staging_geometry_idx1",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_parcels_geometry",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_foreign_key(
        None,
        "permits",
        "parcels",
        ["parcel_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_geospatial_index(
        "idx_parcels_geometry",
        table_name="parcels",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "parcels_staging_geometry_idx1",
        "parcels",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_column("parcels", "original_geoms", schema="processed")
    op.drop_constraint(None, "barnsparcels", schema="processed", type_="foreignkey")
    # ### end Alembic commands ###
