"""recreate foreign keys

Revision ID: f1922b03d5df
Revises: bd3f76ff5747
Create Date: 2025-01-03 11:57:44.055005

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1922b03d5df"
down_revision: Union[str, None] = "bd3f76ff5747"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "barns_staging_geometry_idx",
        table_name="barns",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_barns_geometry",
        "barns",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_index(
        "barnsparcels_staging_barn_id_idx",
        table_name="barnsparcels",
        schema="processed",
    )
    op.drop_index(
        "barnsparcels_staging_parcel_id_idx",
        table_name="barnsparcels",
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnsparcels_barn_id"),
        "barnsparcels",
        ["barn_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnsparcels_parcel_id"),
        "barnsparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "barnsparcels",
        "barns",
        ["barn_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_geospatial_index(
        "cf_annotations_staging_geometry_buffer_idx",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_buffer",
    )
    op.drop_geospatial_index(
        "cf_annotations_staging_geometry_idx",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_index(
        "cf_annotations_staging_raw_coordinates_idx",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="raw_coordinates",
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry",
        "cf_annotations",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry_buffer",
        "cf_annotations",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_cf_annotations_raw_coordinates",
        "cf_annotations",
        ["raw_coordinates"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "label_batches",
        ["batch_name"],
        ["batch_name"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "naip21_qt",
        ["naip_qt_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "barns",
        ["barn_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_index(
        "permits_staging_facilityid_idx1", table_name="permits", schema="processed"
    )
    op.drop_geospatial_index(
        "permits_staging_geometry_idx1",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "idx_permits_geometry",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_permits_facilityid"),
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21",
        ["naip_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.create_foreign_key(
        None,
        "permits",
        "naip21_qt",
        ["naip_qt_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "permits", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_permits_facilityid"),
        table_name="permits",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_permits_geometry",
        table_name="permits",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "permits_staging_geometry_idx1",
        "permits",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "permits_staging_facilityid_idx1",
        "permits",
        ["facilityid"],
        unique=True,
        schema="processed",
    )
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_geospatial_index(
        "idx_cf_annotations_raw_coordinates",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="raw_coordinates",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_geometry_buffer",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_buffer",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_geometry",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "cf_annotations_staging_raw_coordinates_idx",
        "cf_annotations",
        ["raw_coordinates"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "cf_annotations_staging_geometry_idx",
        "cf_annotations",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "cf_annotations_staging_geometry_buffer_idx",
        "cf_annotations",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_constraint(None, "barnsparcels", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_barnsparcels_parcel_id"),
        table_name="barnsparcels",
        schema="processed",
    )
    op.drop_index(
        op.f("ix_processed_barnsparcels_barn_id"),
        table_name="barnsparcels",
        schema="processed",
    )
    op.create_index(
        "barnsparcels_staging_parcel_id_idx",
        "barnsparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        "barnsparcels_staging_barn_id_idx",
        "barnsparcels",
        ["barn_id"],
        unique=False,
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_barns_geometry",
        table_name="barns",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.create_geospatial_index(
        "barns_staging_geometry_idx",
        "barns",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###
