"""update label_batches

Revision ID: f1c1fd57562d
Revises: bc3a16ea76b5
Create Date: 2024-08-15 16:16:30.041856

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f1c1fd57562d"
down_revision: Union[str, None] = "bc3a16ea76b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "label_batches",
        "qt_tile_ids",
        new_column_name="naip_qt_ids",
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        schema="processed",
    )

    op.alter_column(
        "label_batches",
        "qt_tile_ids",
        new_column_name="naip_qt_ids",
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "label_batches",
        "naip_qt_ids",
        new_column_name="qt_tile_ids",
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        schema="raw",
    )

    op.alter_column(
        "label_batches",
        "naip_qt_ids",
        new_column_name="qt_tile_ids",
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        schema="processed",
    )
    # ### end Alembic commands ###
