"""updated models.py structure

Revision ID: f483bd82ed7f
Revises: 6527c15acca6
Create Date: 2024-12-17 16:16:11.343264

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f483bd82ed7f"
down_revision: Union[str, None] = "6527c15acca6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_processed_barnsparcels_barn_id"),
        "barnsparcels",
        ["barn_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnsparcels_parcel_id"),
        "barnsparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_foreign_key(
        None,
        "cf_annotations",
        "barns",
        ["barn_id"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_column("cf_annotations", "features_merged", schema="processed")
    op.drop_column("cf_annotations", "original_ids", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cf_annotations",
        sa.Column(
            "original_ids",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
        schema="processed",
    )
    op.add_column(
        "cf_annotations",
        sa.Column("features_merged", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="processed",
    )
    op.drop_constraint(None, "cf_annotations", schema="processed", type_="foreignkey")
    op.drop_index(
        op.f("ix_processed_barnsparcels_parcel_id"),
        table_name="barnsparcels",
        schema="processed",
    )
    op.drop_index(
        op.f("ix_processed_barnsparcels_barn_id"),
        table_name="barnsparcels",
        schema="processed",
    )
    # ### end Alembic commands ###
