"""added labelbatches table

Revision ID: f4d95042a19b
Revises: cf0bb76fce51
Create Date: 2024-08-14 10:57:59.561255

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f4d95042a19b"
down_revision: Union[str, None] = "cf0bb76fce51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "label_batches",
        sa.Column("qt_tile_ids", postgresql.ARRAY(sa.String()), nullable=True),
        schema="processed",
    )
    op.add_column(
        "label_batches",
        sa.Column("n_facilities", sa.Integer(), nullable=True),
        schema="processed",
    )
    op.add_column(
        "label_batches",
        sa.Column("facility_ids", postgresql.ARRAY(sa.Integer()), nullable=True),
        schema="processed",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("label_batches", "facility_ids", schema="processed")
    op.drop_column("label_batches", "n_facilities", schema="processed")
    op.drop_column("label_batches", "qt_tile_ids", schema="processed")
    # ### end Alembic commands ###
