"""clean schema

Revision ID: f60b55ce3f92
Revises: 5d3d57b768df
Create Date: 2024-08-14 15:48:05.561240

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f60b55ce3f92"
down_revision: Union[str, None] = "5d3d57b768df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_name", sa.String(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("batch_date", sa.Date(), nullable=False),
        sa.Column("batch_metadata", sa.String(), nullable=False),
        sa.Column(
            "qt_tile_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("n_facilities", sa.Integer(), nullable=False),
        sa.Column(
            "facility_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="raw",
    )
    op.drop_constraint(
        "naip21_qt_batch_name_fkey", "naip21_qt", schema="processed", type_="foreignkey"
    )
    op.drop_column("naip21_qt", "batch_name", schema="processed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "naip21_qt",
        sa.Column("batch_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="processed",
    )
    op.create_foreign_key(
        "naip21_qt_batch_name_fkey",
        "naip21_qt",
        "label_batches",
        ["batch_name"],
        ["batch_name"],
        source_schema="processed",
        referent_schema="processed",
    )
    op.drop_table("label_batches", schema="raw")
    # ### end Alembic commands ###
