"""updated relationships

Revision ID: f75e279d1160
Revises: 2aadc4a5dcee
Create Date: 2024-08-13 10:56:34.096167

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f75e279d1160"
down_revision: Union[str, None] = "2aadc4a5dcee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "parcels_permit_ids_fkey", "parcels", schema="processed", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "parcels_permit_ids_fkey",
        "parcels",
        "permits",
        ["permit_ids"],
        ["id"],
        source_schema="processed",
        referent_schema="processed",
    )
    # ### end Alembic commands ###
