"""permits storage table, changed names

Revision ID: f85bb117506e
Revises: 5ef28f3abcae
Create Date: 2025-01-28 19:48:54.041900

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f85bb117506e"
down_revision: Union[str, None] = "5ef28f3abcae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permits_storage",
        sa.Column("vegetative_infiltration_basin_vib_", sa.String(), nullable=True),
        schema="raw",
    )
    op.drop_column("permits_storage", "vegetative_infiltration_basin_vib", schema="raw")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permits_storage",
        sa.Column(
            "vegetative_infiltration_basin_vib",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        schema="raw",
    )
    op.drop_column(
        "permits_storage", "vegetative_infiltration_basin_vib_", schema="raw"
    )
    # ### end Alembic commands ###
