"""updated labelbatchesraw col types

Revision ID: f89cce8d42e4
Revises: e1e565c964a6
Create Date: 2024-08-05 15:38:24.758692

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f89cce8d42e4"
down_revision: Union[str, None] = "e1e565c964a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "label_batches",
        "batch_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.String(),
        existing_nullable=False,
        schema="raw",
    )
    op.alter_column(
        "label_batches",
        "qt_tile_ids",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
        schema="raw",
    )
    op.alter_column(
        "label_batches",
        "n_facilities",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        nullable=False,
        schema="raw",
    )
    op.alter_column(
        "label_batches",
        "facility_ids",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        type_=sa.String(),
        nullable=False,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "label_batches",
        "facility_ids",
        existing_type=sa.String(),
        type_=postgresql.ARRAY(sa.INTEGER()),
        nullable=True,
        schema="raw",
    )
    op.alter_column(
        "label_batches",
        "n_facilities",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        nullable=True,
        schema="raw",
    )
    op.alter_column(
        "label_batches",
        "qt_tile_ids",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
        schema="raw",
    )
    op.alter_column(
        "label_batches",
        "batch_metadata",
        existing_type=sa.String(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        schema="raw",
    )
    # ### end Alembic commands ###
