"""added cluster table

Revision ID: f9330d065d95
Revises: 2574fb84fb79
Create Date: 2025-02-05 16:07:28.519603

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "f9330d065d95"
down_revision: Union[str, None] = "2574fb84fb79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "barnclusters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_barnclusters_geometry",
        "barnclusters",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_table(
        "barnclusterparcels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("barn_cluster_id", sa.Integer(), nullable=False),
        sa.Column("parcel_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["barn_cluster_id"],
            ["processed.barnclusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["processed.parcels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnclusterparcels_barn_cluster_id"),
        "barnclusterparcels",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.create_index(
        op.f("ix_processed_barnclusterparcels_parcel_id"),
        "barnclusterparcels",
        ["parcel_id"],
        unique=False,
        schema="processed",
    )
    op.create_geospatial_table(
        "barns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("barn_cluster_id", sa.Integer(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["barn_cluster_id"],
            ["processed.barnclusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_barns_geometry",
        "barns",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_processed_barns_barn_cluster_id"),
        "barns",
        ["barn_cluster_id"],
        unique=False,
        schema="processed",
    )
    op.create_geospatial_table(
        "cf_annotations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("n_annotations", sa.Integer(), nullable=False),
        sa.Column("clipped_annotation", sa.Boolean(), nullable=False),
        sa.Column("clipped_annotation_empty", sa.Boolean(), nullable=False),
        sa.Column("datasetid", sa.String(), nullable=False),
        sa.Column("itemid", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("creator", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "geometry_buffer",
            Geometry(
                srid=26915,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "raw_coordinates",
            Geometry(spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column("naip_qt_id", sa.String(), nullable=False),
        sa.Column("barn_id", sa.Integer(), nullable=True),
        sa.Column("batch_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["barn_id"],
            ["processed.barns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["batch_name"],
            ["processed.label_batches.batch_name"],
        ),
        sa.ForeignKeyConstraint(
            ["naip_qt_id"],
            ["processed.naip21_qt.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="processed",
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry",
        "cf_annotations",
        ["geometry"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_cf_annotations_geometry_buffer",
        "cf_annotations",
        ["geometry_buffer"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_index(
        "idx_cf_annotations_raw_coordinates",
        "cf_annotations",
        ["raw_coordinates"],
        unique=False,
        schema="processed",
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_cf_annotations_raw_coordinates",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="raw_coordinates",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_geometry_buffer",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry_buffer",
    )
    op.drop_geospatial_index(
        "idx_cf_annotations_geometry",
        table_name="cf_annotations",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("cf_annotations", schema="processed")
    op.drop_index(
        op.f("ix_processed_barns_barn_cluster_id"),
        table_name="barns",
        schema="processed",
    )
    op.drop_geospatial_index(
        "idx_barns_geometry",
        table_name="barns",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("barns", schema="processed")
    op.drop_index(
        op.f("ix_processed_barnclusterparcels_parcel_id"),
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.drop_index(
        op.f("ix_processed_barnclusterparcels_barn_cluster_id"),
        table_name="barnclusterparcels",
        schema="processed",
    )
    op.drop_table("barnclusterparcels", schema="processed")
    op.drop_geospatial_index(
        "idx_barnclusters_geometry",
        table_name="barnclusters",
        schema="processed",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("barnclusters", schema="processed")
    # ### end Alembic commands ###
