"""added LabelBatchesRaw

Revision ID: fc3f23f8b7e8
Revises: c2ab602f747c
Create Date: 2024-08-05 15:24:02.537414

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fc3f23f8b7e8"
down_revision: Union[str, None] = "c2ab602f747c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label_batches",
        sa.Column("batch_nr", sa.Integer(), nullable=False),
        sa.Column("batch_name", sa.String(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("batch_date", sa.Date(), nullable=False),
        sa.Column(
            "batch_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("qt_tile_ids", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("n_facilities", sa.Integer(), nullable=True),
        sa.Column("facility_ids", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.PrimaryKeyConstraint("batch_nr"),
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("label_batches", schema="raw")
    # ### end Alembic commands ###
