"""updated null constraint on geometry

Revision ID: fd91d2bb8358
Revises: 9670d9fb51b1
Create Date: 2024-08-05 17:16:01.440173

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "fd91d2bb8358"
down_revision: Union[str, None] = "9670d9fb51b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cf_annotations",
        "geometry",
        existing_type=Geometry(
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        nullable=True,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cf_annotations",
        "geometry",
        existing_type=Geometry(
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        nullable=False,
        schema="raw",
    )
    # ### end Alembic commands ###
