"""added county column parcel table

Revision ID: fe0f9e589dd8
Revises: 42e1e969e355
Create Date: 2024-11-18 17:18:06.511577

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe0f9e589dd8"
down_revision: Union[str, None] = "42e1e969e355"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parcels", sa.Column("county", sa.String(), nullable=True), schema="processed"
    )
    op.add_column(
        "parcels", sa.Column("county", sa.String(), nullable=True), schema="raw"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parcels", "county", schema="raw")
    op.drop_column("parcels", "county", schema="processed")
    # ### end Alembic commands ###
