"""updated labelbatchesraw col types

Revision ID: ff5fda5f179e
Revises: 3eae41021b8f
Create Date: 2024-08-05 15:59:18.845371

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff5fda5f179e"
down_revision: Union[str, None] = "3eae41021b8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_name", sa.String(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("batch_date", sa.Date(), nullable=False),
        sa.Column("batch_metadata", sa.String(), nullable=False),
        sa.Column("qt_tile_ids", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("n_facilities", sa.Integer(), nullable=False),
        sa.Column("facility_ids", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("label_batches", schema="raw")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label_batches",
        sa.Column("batch_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("batch_size", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("batch_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("batch_metadata", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "qt_tile_ids",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("n_facilities", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "facility_ids",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        schema="raw",
    )
    op.drop_table("label_batches")
    # ### end Alembic commands ###
